openapi: 3.0.0
info:
  title: Title ...
  description: A basic API for ..., documented with OpenAPI and YAML.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server
tags:
  - name: Auth
    description: Authentication and authorization endpoints
  - name: Users
    description: User management endpoints
paths:
  /auth/login:
    post:
      summary: Log in a user
      tags:
        - Auth
      description: Authenticates a user and returns an authentication token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginRequest'
            examples:
              withPassword:
                summary: Login with password
                value:
                  email: admin@havadash.com
                  password: Admin1234*
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginResponse'
              examples:
                withPassword:
                  summary: Login with password
                  value:
                    status: success
                    statusCode: 200
                    message: Login successful
                    data:
                      userId: 123
                      email: admin@havadash.com
                      username: Admin
                      token: eyJhbGciOiJIUzI1NiIs....
                      expiresIn: 3600
        409:
          description: Unauthorized. Invalid email or password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 409
                message: Mevcutta şifre bulunmaktadır.
                data: null
        401:
          description: Unauthorized. Invalid email or password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 401
                message: Unauthorized. Invalid email or password.
                data: null
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 500
                message: Internal server error.
                data: null
  /auth/logout:
    post:
      summary: Log out
      tags:
        - Auth
      description: Logs out a user and invalidates their authentication token.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/logoutRequest'
            example:
              userId: 1
              refreshToken: ey7sd...
      responses:
        200:
          description: User logged out
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/logoutResponse'
              example:
                status: success
                statusCode: 200
                message: User session ended.
                data:
                  result: true
        400:
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 400
                message: Unauthorized post_logout_redirect_uri
                data: null
        409:
          description: Mismatch refresh token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 409
                message: Refresh token mismatch.
                data: null
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baseError'
              example:
                status: error
                statusCode: 500
                message: Internal server error.
                data: null
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Enter the JWT required to access the API here.'
  schemas:
    baseResponse:
      type: object
      properties:
        status:
          type: string
          description: The status of the API call (e.g., success, error).
        statusCode:
          type: integer
          description: HTTP status code.
        message:
          type: string
          description: Explanation of the transaction.
        data:
          type: object
          description: The main data returned by the response. The schema varies depending on the API endpoint.
    baseError:
      allOf:
        - $ref: '#/components/schemas/baseResponse'
        - type: object
          properties:
            data:
              type: null
    loginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: The user's email address.
          pattern: ^[a-zA-Z0-9._]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$
        password:
          type: string
          format: password
          description: The user's password.
          minLength: 8
    loginResponse:
      allOf:
        - $ref: '#/components/schemas/baseResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                userId:
                  type: integer
                email:
                  type: string
                username:
                  type: string
                token:
                  type: string
                expiresIn:
                  type: integer
    loginErrorResponse:
      allOf:
        - $ref: '#/components/schemas/baseError'
        - type: object
          properties:
            data:
              type: object
              properties:
                userId:
                  type: integer
                  description: The unique ID of the created user
                keycloakId:
                  type: string
                  format: uuid
                  description: The unique ID of the keycloak user
                requiredActions:
                  type: array
                  items:
                    type: string
    logoutRequest:
      type: object
      required:
        - userId
        - refreshToken
      properties:
        userId:
          type: integer
          description: The unique ID of the user.
        refreshToken:
          type: string
          description: The refresh token obtained from the login response.
    logoutResponse:
      allOf:
        - $ref: '#/components/schemas/baseResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                result:
                  type: boolean
                  description: Indicates whether the logout was successful.